# Enable compile command to ease indexing with e.g. clangd
set(CMAKE_EXPORT_COMPILE_COMMANDS TRUE)

# Compiler options
target_compile_options(${BUILD_UNIT_0_NAME} PRIVATE
    $<$<COMPILE_LANGUAGE:C>: ${CUBE_CMAKE_C_FLAGS}>
    $<$<COMPILE_LANGUAGE:CXX>: ${CUBE_CMAKE_CXX_FLAGS}>
    $<$<COMPILE_LANGUAGE:ASM>: ${CUBE_CMAKE_ASM_FLAGS}>
)

# Linker options
target_link_options(${BUILD_UNIT_0_NAME} PRIVATE ${CUBE_CMAKE_EXE_LINKER_FLAGS})

# Add sources to executable/library
target_sources(${BUILD_UNIT_0_NAME} PRIVATE
    "Core/Src/app/app.c"
    "Core/Src/common/button_fsm.c"
    "Core/Src/common/log.c"
    "Core/Src/common/platform_gpio.c"
    "Core/Src/common/platform_port.c"
    "Core/Src/freertos.c"
    "Core/Src/gpio.c"
    "Core/Src/main.c"
    "Core/Src/rtos/rtos_app.c"
    "Core/Src/rtos/rtos_button.c"
    "Core/Src/rtos/rtos_log_service.c"
    "Core/Src/rtos/rtos_monitor.c"
    "Core/Src/rtos/rtos_probe.c"
    "Core/Src/stm32f4xx_hal_msp.c"
    "Core/Src/stm32f4xx_hal_timebase_tim.c"
    "Core/Src/stm32f4xx_it.c"
    "Core/Src/syscalls.c"
    "Core/Src/system_stm32f4xx.c"
    "Core/Src/test/runtime/test_baremetal_runner.c"
    "Core/Src/test/runtime/test_rtos_runner.c"
    "Core/Src/test/runtime/test_rtos_runtime.c"
    "Core/Src/test/runtime/test_timer.c"
    "Core/Src/test/tc_00/tc_000_firmware_execution_verification.c"
    "Core/Src/test/tc_00/tc_001_debug_attach_reset.c"
    "Core/Src/test/tc_00/tc_002_clock_sanity.c"
    "Core/Src/test/tc_01/tc_010_led_gpio.c"
    "Core/Src/test/tc_01/tc_011_button_polling.c"
    "Core/Src/test/tc_01/tc_012_single_click_toggle.c"
    "Core/Src/test/tc_01/tc_013_long_press_toggle_once.c"
    "Core/Src/test/tc_02/tc_020_uart_sanity.c"
    "Core/Src/test/tc_02/tc_021_boot_log_format.c"
    "Core/Src/test/tc_02/tc_022_button_event_uart_mapping.c"
    "Core/Src/test/tc_03/tc_030_timing_interval_accuracy_validation.c"
    "Core/Src/test/tc_03/tc_031_button_debounce_stability_validation.c"
    "Core/Src/test/tc_03/tc_032_cpu_load_impact_on_button_detection.c"
    "Core/Src/test/tc_04/tc_040_button_bounce_bug_injection.c"
    "Core/Src/test/tc_04/tc_041_long_press_repeated_event_defect.c"
    "Core/Src/test/tc_04/tc_042_uart_event_omission_defect.c"
    "Core/Src/test/tc_05/tc_050_debounce_fix_validation.c"
    "Core/Src/test/tc_05/tc_051_long_press_one_shot_fix_validation.c"
    "Core/Src/test/tc_05/tc_052_uart_event_mapping_fix_validation.c"
    "Core/Src/test/tc_06/tc_060_regression_after_button_fix.c"
    "Core/Src/test/tc_06/tc_061_related_function_regression_summary.c"
    "Core/Src/test/tc_06/tc_062_rapid_input_stress_test.c"
    "Core/Src/test/tc_06/tc_063_long_duration_stability_test.c"
    "Core/Src/test/tc_06/tc_064_power_cycle_recovery_validation.c"
    "Core/Src/test/tc_06/tc_065_reset_recovery_observation.c"
    "Core/Src/test/tc_06/tc_066_fault_log_safe_state_validation.c"
    "Core/Src/test/tc_rtos/tc_030_rtos.c"
    "Core/Src/test/tc_rtos/tc_032_rtos.c"
    "Core/Src/test/tc_rtos/tc_042_rtos.c"
    "Core/Src/test/tc_rtos/tc_063_rtos.c"
    "Core/Src/test/tc_rtos/tc_066_rtos.c"
    "Core/Src/test/verify/toggle_verifier.c"
    "Core/Src/usart.c"
    "Core/Startup/startup_stm32f411retx.s"
    "Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c"
    "Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c"
    "Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c"
    "Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c"
    "Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c"
    "Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c"
    "Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c"
    "Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c"
    "Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c"
    "Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c"
    "Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c"
    "Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c"
    "Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c"
    "Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c"
    "Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c"
    "Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c"
    "Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c"
    "Middlewares/Third_Party/FreeRTOS/Source/croutine.c"
    "Middlewares/Third_Party/FreeRTOS/Source/event_groups.c"
    "Middlewares/Third_Party/FreeRTOS/Source/list.c"
    "Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c"
    "Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c"
    "Middlewares/Third_Party/FreeRTOS/Source/queue.c"
    "Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c"
    "Middlewares/Third_Party/FreeRTOS/Source/tasks.c"
    "Middlewares/Third_Party/FreeRTOS/Source/timers.c"
)